/*
 * 
 */
package br.com.sicoob.cca.entidades.negocio.enums;

/**
 * @author Marco.Nascimento
 */
public enum EnumTipoHistoricoCCA {
	
	/** O atributo COD_TIPO_HIST_CCA_SUBSC. */
	COD_TIPO_HIST_CCA_SUBSC(1,"SUBSCRICAO DE CAPITAL"),
	
	/** O atributo COD_TIPO_HIST_CCA_SUBSC_BAIXA. */
	COD_TIPO_HIST_CCA_SUBSC_BAIXA(2,"BAIXA DE SUBSCRICAO"),
	
	/** O atributo COD_TIPO_HIST_CCA_SUBSC_TRANSF_BAIXA_SUBSC. */
	COD_TIPO_HIST_CCA_SUBSC_TRANSF_BAIXA_SUBSC(4,"TRANSFERENCIA - BAIXA SUBSCRICAO"),
	
	/** O atributo COD_TIPO_HIST_CCA_SUBSC_TRANSF_SUBS. */
	COD_TIPO_HIST_CCA_SUBSC_TRANSF_SUBS(5,"TRANSFERENCIA - SUBSCRICAO"),
	
	/** O atributo COD_TIPO_HIST_CCA_SUBSC_IMPLANT. */
	COD_TIPO_HIST_CCA_SUBSC_IMPLANT(6,"SUBSCRICAO ATE DATA DE IMPLANTACAO"),
	
	/** O atributo COD_TIPO_HIST_CCA_SUBSC_CANC. */
	COD_TIPO_HIST_CCA_SUBSC_CANC(7,"CANCELAMENTO SUBSCRICAO"),
	
	/** O atributo COD_TIPO_HIST_CCA_SUBSC_INCORP. */
	COD_TIPO_HIST_CCA_SUBSC_INCORP(8,"SUBSCRICAO ATE DATA DE INCORPORACAO"),
	
	/** O atributo COD_TIPO_HIST_CCA_SUBSC_PROCAPCRED. */
	COD_TIPO_HIST_CCA_SUBSC_PROCAPCRED(9,"SUBSCRICAO PROPCAPCRED"),
	
	/** O atributo COD_TIPO_HIST_CCA_SUBSC_ESTORNO_SUBS. */
	COD_TIPO_HIST_CCA_SUBSC_ESTORNO_SUBS(10,"ESTORNO CAPITAL SUBSCRITO"),
	
	/** O atributo COD_TIPO_HIST_CCA_SUBSC_IRRF. */
	COD_TIPO_HIST_CCA_SUBSC_IRRF(17,"IRRF S/ JUROS AO CAPITAL SUBSCRITO"),
	
	/** O atributo COD_TIPO_HIST_CCA_SUBSC_COTASPARTES. */
	COD_TIPO_HIST_CCA_SUBSC_COTASPARTES(62,"SUBSCRICAO COTAS-PARTES"),
	
	/** O atributo COD_TIPO_HIST_CCA_INTEG_IMPLANT. */
	COD_TIPO_HIST_CCA_INTEG_IMPLANT(111,"INTEGRALIZACAO ATE DATA IMPLANTACAO"),
	
	/** O atributo COD_TIPO_HIST_CCA_INTEG_INCORP. */
	COD_TIPO_HIST_CCA_INTEG_INCORP(112,"INTEGRALIZACAO ATE DATA INCORPORACAO"),
	
	/** O atributo COD_TIPO_HIST_CCA_INTEG_BANCO. */
	COD_TIPO_HIST_CCA_INTEG_BANCO(130,"INTEGRALIZACAO VIA BANCO"),
	
	/** O atributo COD_TIPO_HIST_CCA_INTEG_FOLHA. */
	COD_TIPO_HIST_CCA_INTEG_FOLHA(131,"INTEGRALIZACAO VIA FOLHA"),
	
	/** O atributo COD_TIPO_HIST_CCA_INTEG_CAIXA. */
	COD_TIPO_HIST_CCA_INTEG_CAIXA(100,"INTEGRALIZACAO VIA CAIXA"),
	
	/** O atributo COD_TIPO_HIST_CCA_INTEG_CONTA. */
	COD_TIPO_HIST_CCA_INTEG_CONTA(102,"INTEGRALIZACAO VIA CONTA"),
	
	/** O atributo COD_TIPO_HIST_CCA_INTEG_COBR. */
	COD_TIPO_HIST_CCA_INTEG_COBR(103,"INTEGRALIZACAO VIA COBRANCA"),
	
	/** O atributo COD_TIPO_HIST_CCA_INTEG_RESERVA. */
	COD_TIPO_HIST_CCA_INTEG_RESERVA(109,"INTEGRALIZACAO VIA RESERVA"),
	
	/** O atributo COD_TIPO_HIST_CCA_INTEG_JUROS. */
	COD_TIPO_HIST_CCA_INTEG_JUROS(107,"INTEGRALIZACAO JUROS"),
	
	/** O atributo COD_TIPO_HIST_CCA_INTEG_RATEIO. */
	COD_TIPO_HIST_CCA_INTEG_RATEIO(108,"INTEGRALIZACAO RATEIO"),
	
	/** O atributo COD_TIPO_HIST_CCA_INTEG_PROCAPCRED. */
	COD_TIPO_HIST_CCA_INTEG_PROCAPCRED(113,"INTEGRALIZACAO PROCAPCRED"),
	
	/** O atributo COD_TIPO_HIST_CCA_INTEG_COTASPARTES. */
	COD_TIPO_HIST_CCA_INTEG_COTASPARTES(63,"INTEGRALIZACAO COTAS-PARTES"),
	
	/** O atributo COD_TIPO_HIST_CCA_INTEG_PONTOS_CARTAO. */
	COD_TIPO_HIST_CCA_INTEG_PONTOS_CARTAO(132,"INTEGRALIZACAO PONTOS CARTAO"),
	
	/** O atributo COD_TIPO_HIST_CCA_INTEG_BOLETO_COMPE. */
	COD_TIPO_HIST_CCA_INTEG_BOLETO_COMPE(133, "INTEGRALIZAÇÃO VIA BOLETO BANCÁRIO - COMPE"),
	
	/** O atributo COD_TIPO_HIST_CCA_INTEG_BOLETO_CAIXA. */
	COD_TIPO_HIST_CCA_INTEG_BOLETO_CAIXA(135, "INTEGRALIZAÇÃO VIA BOLETO BANCÁRIO - CAIXA"),
	
	/** O atributo COD_TIPO_HIST_CCA_INTEG_BOLETO_CCO. */
	COD_TIPO_HIST_CCA_INTEG_BOLETO_CCO(136, "INTEGRALIZAÇÃO VIA BOLETO BANCÁRIO - CONTA CORRENTE"),

	/** O atributo COD_TIPO_HIST_CCA_INTEG_CARTAO_CREDITO. */
	COD_TIPO_HIST_CCA_INTEG_CARTAO_CREDITO(134,"INTEGRALIZACAO CARTAO CREDITO"),
	
	/** O atributo COD_TIPO_HIST_CCA_INTEG_OUTROS_BANCOS. */
	COD_TIPO_HIST_CCA_INTEG_OUTROS_BANCOS(137,"INTEGRALIZACAO VIA OUTROS BANCOS"),
	
	/** O atributo COD_TIPO_HIST_CCA_INTEG_CONTA_DIGITAL. */	
	COD_TIPO_HIST_CCA_INTEG_CONTA_DIGITAL(138,"INTEGRALIZACAO VIA CONTA DIGITAL"),	
	
	/** O atributo COD_TIPO_HIST_CCA_INTEG_TRANSF_REST. */
	COD_TIPO_HIST_CCA_INTEG_TRANSF_REST(101,"TRANSF. INTEGRALIZACAO P/ A RESTITUIR"),
	
	/** O atributo COD_TIPO_HIST_CCA_INTEG_TRANSF_BAIXA. */
	COD_TIPO_HIST_CCA_INTEG_TRANSF_BAIXA(105,"TRANSFERENCIA - BAIXA INTEGRALIZACAO"),
	
	/** O atributo COD_TIPO_HIST_CCA_INTEG_TRANSF. */
	COD_TIPO_HIST_CCA_INTEG_TRANSF(106,"TRANSFERENCIA - INTEGRALIZACAO"),
	
	/** O atributo COD_TIPO_HIST_CCA_INTEG_CANC_PARC_DEV. */
	COD_TIPO_HIST_CCA_INTEG_CANC_PARC_DEV(110,"INTEGRALIZACAO-CANC PARCELA DEVOLUCAO"),
	
	/** O atributo COD_TIPO_HIST_CCA_INTEG_ESTORNO_CAP_INTEG. */
	COD_TIPO_HIST_CCA_INTEG_ESTORNO_CAP_INTEG(114,"ESTORNO CAPITAL INTEGRALIZADO"),
	
	/** O atributo COD_TIPO_HIST_CCA_INTEG_IRRF. */
	COD_TIPO_HIST_CCA_INTEG_IRRF(117,"IRRF S/ JUROS AO CAPITAL INTEGRALIZADO"),
	
	/** O atributo COD_TIPO_HIST_CCA_INTEG_BAIXA_INTEG_DEVOL. */
	COD_TIPO_HIST_CCA_INTEG_BAIXA_INTEG_DEVOL(120,"BAIXA DE INTEGRALIZACAO - DEVOLUCAO"),
				
	/** O atributo COD_TIPO_HIST_CCA_DEV_TRANSF_INTEG. */
	COD_TIPO_HIST_CCA_DEV_TRANSF_INTEG(201,"TRANSF. A RESTITUIR DE INTEGRALIZACAO"),
	
	/** O atributo COD_TIPO_HIST_CCA_DEV_CAIXA. */
	COD_TIPO_HIST_CCA_DEV_CAIXA(202,"DEVOL. CAPITAL VIA CAIXA"),
	
	/** O atributo COD_TIPO_HIST_CCA_DEV_BANCO. */
	COD_TIPO_HIST_CCA_DEV_BANCO(203,"DEVOL. CAPITAL VIA BANCO"),
	
	/** O atributo COD_TIPO_HIST_CCA_DEV_CONTA. */
	COD_TIPO_HIST_CCA_DEV_CONTA(204,"DEVOL. CAPITAL VIA C/C"),
	
	/** O atributo COD_TIPO_HIST_CCA_DEV_JUROS_COOP_DESL. */
	COD_TIPO_HIST_CCA_DEV_JUROS_COOP_DESL(207,"CREDITO JUROS - COOP DESLIGADO"),
	
	/** O atributo COD_TIPO_HIST_CCA_DEV_RATEIO_COOP_DESL. */
	COD_TIPO_HIST_CCA_DEV_RATEIO_COOP_DESL(208,"CREDITO RATEIO - COOP DESLIGADO"),
	
	/** O atributo COD_TIPO_HIST_CCA_DEV_INCOPORACAO. */
	COD_TIPO_HIST_CCA_DEV_INCOPORACAO(209,"CREDITO INCORPORAÇÃO"),
	
	/** O atributo COD_TIPO_HIST_CCA_DEV_CANC_PARC_DEV. */
	COD_TIPO_HIST_CCA_DEV_CANC_PARC_DEV(210,"CANCELAMENTO PARCELA DEVOLUCAO"),
	
	/** O atributo COD_TIPO_HIST_CCA_DEV_CRED_ESTORNO_CAP. */
	COD_TIPO_HIST_CCA_DEV_CRED_ESTORNO_CAP(211,"CREDITO ESTORNO CAPITAL"),
	
	/** O atributo COD_TIPO_HIST_CCA_DEV_ESTORNO_CAP. */
	COD_TIPO_HIST_CCA_DEV_ESTORNO_CAP(212,"ESTORNO CAPITAL"),
	
	/** O atributo COD_TIPO_HIST_CCA_DEV_IRRF. */
	COD_TIPO_HIST_CCA_DEV_IRRF(217,"IRRF S/ JUROS AO CAPITAL A DEVOLVER"),
			
	/** O atributo COD_TIPO_HIST_CCA_NAO_SENS_PROV_MENSAL_JUROS. */
	COD_TIPO_HIST_CCA_NAO_SENS_PROV_MENSAL_JUROS(901,"PROVISAO MENSAL DE JUROS"),
	
	/** O atributo COD_TIPO_HIST_CCA_NAO_SENS_PROV_ANUAL_JUROS. */
	COD_TIPO_HIST_CCA_NAO_SENS_PROV_ANUAL_JUROS(902,"PROVISAO ANUAL DE JUROS"),
	
	/** O atributo COD_TIPO_HIST_CCA_NAO_SENS_ESTORNO. */
	COD_TIPO_HIST_CCA_NAO_SENS_ESTORNO(999,"ESTORNO DE PROVISAO"),
	
	COD_TIPO_HIST_CCA_ESTORNO_GRUPO_SUBSCRICAO(99, "ESTORNO GRUPO SUBSCRIÇÃO"),
	
	COD_TIPO_HIST_CCA_ESTORNO_GRUPO_INTEGRALIZACAO(199, "ESTORNO GRUPO INTEGRALIZAÇÃO"),
	
	COD_TIPO_HIST_CCA_ESTORNO_GRUPO_DEVOLUCAO(299, "ESTORNO GRUPO DEVOLUÇÃO");

	/** O atributo codigo. */
	private Integer codigo;
	
	/** O atributo descricao. */
	private String descricao;
	
	/**
	 * Instancia um novo EnumTipoHistoricoCCA.
	 *
	 * @param codigo o valor de codigo
	 * @param descricao o valor de descricao
	 */
	private EnumTipoHistoricoCCA(Integer codigo, String descricao) {
		this.codigo = codigo;
		this.descricao = descricao;
	}

	/**
	 * Recupera o valor de codigo.
	 *
	 * @return o valor de codigo
	 */
	public Integer getCodigo() {
		return codigo;
	}

	/**
	 * Recupera o valor de descricao.
	 *
	 * @return o valor de descricao
	 */
	public String getDescricao() {
		return descricao;
	}
}