package br.com.sicoob.sisbr.cca.processamento.constantes;

public enum EnumFechamento {
	ID_PROCESSO_BAIXA_PARC_CCO_SQL(1),
	ID_PROCESSO_BAIXA_PARC_CCO_DB2(2),
	ID_PROCESSO_BAIXA_INT_DEB_INDET_SQL(3),
	ID_PROCESSO_BAIXA_INT_DEB_INDET_DB2(4),
	ID_PROCESSO_GERAR_CALC_PROV_JUROS(5),
	ID_PROCESSO_DESTINA_JUROS_SQL(6),
	ID_PROCESSO_DESTINA_JUROS_DB2(7),
	ID_PROCESSO_ATUALIZA_MOV_LANC_SQL(8),
	ID_PROCESSO_ATUALIZA_MOV_LANC_DB2(9),
	ID_PROCESSO_GERAR_INFO_ACUMULADAS(10),
	ID_PROCESSO_GRAVA_SALDO_CAPITAL_SOCIAL_INT(11),
	ID_PROCESSO_GERAR_INFO_CALC_VAR(12),
	ID_PROCESSO_PROCESSAR_OP_FINANC_CONTABIL(13),
	ID_PROCESSO_MECANISMO_CONTABIL(14),
	ID_PROCESSO_ATUALIZAR_DATA(15),
	ID_PROCESSO_REL_SALDO_CONTA_CAPITAL(16),
	ID_PROCESSO_REL_POSICAO_DIARIA_CARTEIRA(17),
	ID_PROCESSO_REL_LANC_CONTABIL(18),
	ID_PROCESSO_REL_RESUMO_LANC(19),
	ID_PROCESSO_REL_LANC_SINTETICO(20),
	ID_PROCESSO_REL_LANC_ANALITICO(21),
	ID_PROCESSO_REL_CONCILIACAO_CONTABIL(22);
	
	private int intValue;
	
	EnumFechamento(int intValue) {
		this.intValue = intValue;
	}
	
	public int getIntValue() {
		return this.intValue;
	}
	
}
